#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

#------------------------------- hemodynamic4Foam project -------------------------------#
#Author
    #Ehsan Golab, SUT. All rights reserved.
    #Ehsan1996Golab@gmail.com

#--------------------------------------------------------------------------------------#

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# cleancase is function that removes the files and directories.(rm -f : remove the file, rm -r : remove the directory).
cleancase ()
{
    rm -r Gnu*
    rm -r processor*
}


postProcess ()
{
    helicity4HD
    LNH4HD
    TAH4HD
    TAHI4HD
    WSS4HD
    magWSS4HD
    TAWSS4HD
    magTAWSS4HD
    OSI4HD
    RRT4HD
}

# (getApplication) is an command to find the solver name from the controlDict file. Also, ($) use for the variable.
application=$(getApplication)

#cleancase
./Allclean


echo run blockMesh ...
#blockMesh
fluentMeshToFoam fluent-coarse.msh
transformPoints -scale '(0.001 0.001 0.001)'
createPatch -overwrite


#convert mesh to STL
surfaceMeshTriangulate CCAModel.stl


echo run solver ...
#$application
hemodynamic4HD
postProcess

# -------------------------------------------------------------------------- end-of-file






