#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
#set -x

#------------------------------- hemodynamic4Foam project -------------------------------#
#Author
    #Ehsan Golab, SUT. All rights reserved.
    #Ehsan1996Golab@gmail.com

#--------------------------------------------------------------------------------------#


wmake libso foam4HD
wmake libso finiteVolume4HD
transportModels4HD/Allwmake
postProcessing4HD/Allwmake
# ----------------------------------------------------------------- end-of-file
