#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

#------------------------------- hemodynamic4Foam project -------------------------------#
#Author
    #Ehsan Golab, SUT. All rights reserved.
    #Ehsan1996Golab@gmail.com

#--------------------------------------------------------------------------------------#

# Parse arguments for library compilation
targetType=libso

wmake $targetType utilities4HD

# ----------------------------------------------------------------- end-of-file
